---
services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    user: 5050:5050
    ports:
      - 5050:80
    volumes:
      - my_pgadmin:/var/lib/pgadmin
volumes:
  my_pgadmin:
