---
version: '3'  # optional since v1.27.0
services:
  minio:
    image: docker.io/minio/minio:RELEASE.2022-09-25T15-44-53Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # - MINIO_DEFAULT_BUCKETS=my-default-bucket  # It only works for bitnami/minio image
    volumes:
      - my_minio:/data
    command:
      - server
      - /data
      - --console-address
      - :9001
  # https://github.com/minio/minio/issues/4769
  createbuckets:
    image: docker.io/minio/mc:RELEASE.2022-09-16T09-16-47Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/my-default-bucket;
      /usr/bin/mc mb myminio/my-default-bucket;
      /usr/bin/mc policy set download myminio/my-default-bucket;
      exit 0;
      "
volumes:
  my_minio:
