---
version: '3'  # optional since v1.27.0
services:
  minio:
    image: docker.io/bitnami/minio:2024.1.18
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=my-bucket1,my-bucket2
    volumes:
      - bitnami-minio:/data
volumes:
  bitnami-minio:
