---
version: '3.8'  # optional since v1.27.0
services:
  minio:
    image: docker.io/minio/minio:RELEASE.2022-08-08T18-34-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - my_minio:/data
    command:
      - server
      - /data
      - --console-address
      - :9001
volumes:
  my_minio:
